name: Build and upload Docker image

on:
  push:
    branches:
      - main

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Build images
        env:
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          printenv DOCKERHUB_PASSWORD | 
          docker buildx build \
            --platform linux \
            --tag cooletijdgast/discord-soundbot:latest \
            --push \
            .
